service: workshop-${self:custom.name}

frameworkVersion: "3"

custom:
  name: rajan

provider:
  name: aws
  runtime: nodejs18.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
